version: "2"
services:
  mongo:
    image: mongo
    networks:
      - chatbotnetwork
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
	  
  chiron-augment:
    image: digite/chiron-augment:latest
    networks:
      - chatbotnetwork
    container_name: chiron-augment
    hostname: chiron-augment
    depends_on:
      - mongo
    ports:
      - 8001:8000
    volumes:
      - chiron_augment_tmp:/root/.cache/
    environment:
      mongo_url: "mongodb://mongo:27017"

  chiron-api:
    image: digite/chiron-api:latest
    networks:
      - chatbotnetwork
    container_name: chiron-api
    hostname:chiron-api
    depends_on:
      - mongo
      - chiron-augment
    ports:
      - 81:80
    volumes:
      - chiron_models:/app/models
      - chiron_tmp:/root/.cache/
    environment:
      mongo_url: "mongodb://mongo:27017"
      mongo_db: "chiron"
      SECRET_KEY: "b9d01861392757c66daaf1f214268e2739a5baac935071d06e2ea71a66dc5bcd"
      augmentation_url: "http://chiron-augment:8001/questions"
      test_conversation_db: "chiron_conversations"

  chiron-ui:
    image: digite/chiron-ui:latest
    networks:
      - chatbotnetwork
    container_name: chiron-ui
    hostname: chiron-ui
    depends_on:
      - chiron-api
    ports:
      - 80:8080
    environment:
      server: "http://chiron-api:81/"
	  
  duckling:
    image: rasa/duckling
    networks:
      - chatbotnetwork
    container_name: duckling
    hostname: duckling
    ports:
      - 8000:8000

networks:
  chatbotnetwork:

volumes:
  chiron_models:
  chiron_tmp:
  chiron_augment_tmp:
  mongo_data: