version: "2"
services:
  mongo:
    image: mongo
    networks:
      - chatbotnetwork
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
	  
  bot-augment-api:
    image: digite/rasa-dx-augment:0.1
    networks:
      - chatbotnetwork
    container_name: bot-augment-api
    hostname: bot-augment-api
    depends_on:
      - mongo
    ports:
      - 8001:8000
    volumes:
      - augment_tmp:/root/.cache/
    environment:
      mongo_url: "mongodb://mongo:27017"

  bot-trainer-api:
    image: digite/rasa-dx-trainer:latest
    networks:
      - chatbotnetwork
    container_name: bot-trainer-api
    hostname: bot-trainer-api
    depends_on:
      - mongo
      - bot-augment-api
    ports:
      - 81:80
    volumes:
      - trainer_models:/app/models
      - trainer_tmp:/root/.cache/
    environment:
      mongo_url: "mongodb://mongo:27017"
      mongo_db: "bot-trainer"
      SECRET_KEY: "b9d01861392757c66daaf1f214268e2739a5baac935071d06e2ea71a66dc5bcd"
      augmentation_url: "http://bot-augment-api:8001/questions"

  bot-trainer-ui:
    image: digite/rasa-dx-ui:latest
    networks:
      - chatbotnetwork
    container_name: bot-trainer-ui
    hostname: bot-trainer-ui
    depends_on:
      - bot-trainer-api
    ports:
      - 80:8080
    environment:
      server: "http://bot-trainer-api:81/"
	  
  duckling:
    image: rasa/duckling
    networks:
      - chatbotnetwork
    container_name: duckling
    hostname: duckling
    ports:
      - 8000:8000

networks:
  chatbotnetwork:

volumes:
  trainer_models:
  trainer_tmp:
  augment_tmp:
  mongo_data: