name: Vulnerability Scan

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull ${{ secrets.DOCKER_IMAGE_AUGMENT }}
      - uses: homoluctus/gitrivy@v2
        name: Scanning augment image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ secrets.DOCKER_IMAGE_AUGMENT }}
